language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt  
env:
  global:
    - export TZ="Asia/Jerusalem"
    - RABBITMQ_NODE_IP_ADDRESS="0.0.0.0"
script:
  - pytest --cov-report term --cov=cortex
addons:
  apt:
    packages:
      - rabbitmq-server
services:
  - mongodb
  - rabbitmq
after_success:
  - codecov