# docker-compose version tag.
version: "3"

# Define docker-composes services
services:

  # Color Image Parser Container
  parser_color_image:
    # Path of Dockerfile
    build: 
      context: .

    # The command to execute once the image is created.
    # command: python ./code.py

    # Container can access to the 'localhost' of the computer.
    network_mode: host
    
    # Setting common volume, to share files among containers
    volumes:
      - ./:/usr/src/app
    
    # Define port so it would be accessible from outside the container
    # [port on machine]:[port in the container]
    ports:
      - 5672:5672

    # Defining environment variables      
    environment:
      PARSER: color_image
  
  # Server Container
  server:
    # Path of Dockerfile
    build: 
      context: .

    # The command to execute once the image is created.
    # command: python ./code.py

    # Container can access to the 'localhost' of the computer.
    network_mode: host
    
    # Setting common volume, to share files among containers
    volumes:
      - ./:/usr/src/app
    
    # Define port so it would be accessible from outside the container
    # [port on machine]:[port in the container]
    ports:
      - 8000:8000

    # Defining environment variables      
    environment:
      RUN: SERVER

  # Client Container
  # FOR END-TO-END TESTING
  client:
    build: 
      context: .

    # The command to execute once the image is created.
    # Client waits for server to accept connections before starting
    command: ["./wait-for-it.sh", "server:8000"]

    # Container can access to the 'localhost' of the computer.
    network_mode: host

    # Setting common volume, to share files among containers
    volumes:
      - ./:/usr/src/app

    # Defining environment variables
    environment:
      RUN: CLIENT

    # Defining client won't start till other specified conatiners are ready
    depends_on:
      - server
    