# Message Queue configuration version tag.
version: "1"

# Default Header
message_queue:
    # Type
    server:
        # Category : Publishers
        publishers:    
            # Item
            - snapshots:
                # Context fields values
                exchange_type   : 'fanout'
                exchange_name   : 'raw'
                queue_name      : ''
                binding_keys    : 

    # Type
    parser:
        # Category : Publishers
        publishers:
            # Item
            - parsed_snapshot:
                # Context fields values
                exchange_type   : 'fanout'
                exchange_name   : '<name>'
                queue_name      : ''
                binding_keys    : 
        # Category : Consumers
        consumers:   
            # Item
            - snapshots:
                # Context fields values
                exchange_type   : 'fanout'
                exchange_name   : 'raw'
                queue_name      : ''
                binding_keys    : [ 'snapshot' ]
                
    # Type
    saver:
        # Category : Consumers
        consumers:   
            # Item
            - parser.color_image:
                # Context fields values
                exchange_type   : 'fanout'
                exchange_name   : 'color_image.parser'
                queue_name      : 'color_image'
                binding_keys    : [ 'color_image.*' ]
            # Item
            - parser.depth_image:
                # Context fields values
                exchange_type   : 'fanout'
                exchange_name   : 'depth_image.parser'
                queue_name      : 'depth_image'
                binding_keys    : [ 'depth_image.*' ]
            # Item
            - parser.pose:
                # Context fields values
                exchange_type   : 'fanout'
                exchange_name   : 'pose.parser'
                queue_name      : 'pose'
                binding_keys    : [ 'pose.*' ]
            # Item
            - parser.user_feelings:
                # Context fields values
                exchange_type   : 'fanout'
                exchange_name   : 'user_feelings.parser'
                queue_name      : 'user_feelings'
                binding_keys    : [ 'user_feelings.*' ]
                